### ISSUE TITLE
Add professions plugin

### ISSUE THREAD

**Issue by alyphen** [RP-Kit/RPKit#38]
Add a plugin that allows players to level up in a chosen profession and craft items related to that profession.

**Comment by alyphen** [comment]
Commands:
/profession list - Lists professions
/profession set [profession] - Set profession to a chosen profession. Should have permissions nodes to set profession when it is already set, or set for another player (via /profession set [player] [profession]
/profession experience add (player) (profession) [amount] - Add experience to a player's active character in a profession
/profession experience remove (player) (profession) [amount] - Remove experience from a player's active character in a profession
/profession experience view (player) (profession) - View experience for a player in their active character's profession.

Config should determine which items a profession can craft at any given level.
To make this less tedious to configure, first there should be a section of restricted items, then for each profession there should be levels with the materials they unlock.
For instance:

```yml
crafting:
  restricted-items:
  - BREAD
  - CAKE
  - PUMPKIN_SEEDS
professions:
  cook:
    crafting:
      '1':
      - BREAD
      - PUMPKIN_SEEDS
      '5':
      - CAKE
```

There should also be a configurable experience gain formula for each profession. This should be similar to the experience plugin:

```yml
professions:
  cook:
    levels:
      max-level: 100
    experience:
      formula: '(level - 1) * 1000'
```

Lastly each item crafted/smelted/etc should have a configurable exp gain for each profession.

```yml
professions:
  cook:
    experience:
      items:
        BREAD: 2
```

So essentially:
* Items are restricted to certain professions at certain levels
* Crafting items allows the player to level up in a profession
* Levelling up allows the player to craft new items
