### ISSUE TITLE
Add general crafting/smelting/mining skill plugin

### ISSUE THREAD

**Issue by alyphen** [RP-Kit/RPKit#40]
Add a basic plugin that allows players to progress in skill mining/crafting/smelting items

**Comment by alyphen** [comment]
Each item should have an experience value for each character.
The amount of an item produced by performing an action should be configurable, and once #33 is done, also the quality.
 
For instance:

```yml
crafting:
  BREAD:
    '0':
      quality: Poor
      amount: 0.25
    '100':
      quality: Adequate
      amount: 1
    '200':
      quality: Good
      amount: 3
```

Crafting an item once should give one experience, and experience should cap out at the highest level configured for that item.

If an item has no configuration entry, no experience should be gained and no modification to its creation should be done.

If the amount configured is fractional (i.e. 0 < x < 1) then there should be a chance of crafting the item. For instance 0.25 should indicate a 1 in 4 chance of crafting the item. (in order to do this, use 1 / amount, generate a random up to the result, and check if it == 0)
